KOBOT-13/2024OpenSW-BACK

- requirements.txt
- users/models.py
- pip install -r requirements.txt 한번씩 해주세요!
- simple-jwt란? 
Simpe-JWT는 DRF을 위해 JSON Web Token authentication을 제공한다.
라이브러리 사용 방법은 djangorestframework-jwt 와 비슷하고 처음 인증할때, access_token, refresh_token 둘 다 보내준다. 
- 링크 읽어보면 좋아요
https://velog.io/@chaeri93/DRF-Simple-jwt%EB%A1%9C-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B8%B0%EB%8A%A5
> Chore: simple-jwt 패키지 추가

- books/serializers.py
- books/urls.py
- books/views.py
- ossKobot/settings.py
- ossKobot/urls.py
- quizzes/serializers.py
- quizzes/urls.py
- quizzes/views.py
각 앱 내 모델들의 serializer, urls를 정의하고 ViewSet을 구현하였습니다.
> Feat: 모델 CRUD 구현

- books/urls.py
- books/views.py
book_id를 넣어서 같은 book_id의 등장인물을 반환하는 API를 구현하였습니다.
`http://127.0.0.1:8000/api/books/{book_id}/characters/` url을 사용하여 book_id를 통해 등장인물들의 List를 반환할 수 있습니다.
`http://127.0.0.1:8000/api/books/1/characters/`로 접속하였을 때의 결과는 아래와 같습니다.
(book_id 1으로 아기돼지3형제 책을 db에 넣어두었음)
> Feat: 책 별 등장인물 검색 API 구현 

- books/models.py
- dialogs/admin.py
- dialogs/models.py
- dialogs/serializers.py
- dialogs/urls.py
- dialogs/views.py
- quizzes/models.py
dialogs 앱 내에서 Conversation와 Message 모델을 구현하였습니다.
> Feat: dialogs 앱 내 모델 구현

- ossKobot/settings.py
- users/models.py
> Feat: 유저 모델 erd에 맞게 수정했습니다.

- audios/admin.py
- audios/apps.py
- audios/models.py
- audios/serializers.py
- audios/tests.py
- audios/urls.py
- audios/views.py
> Feat: 텍스트 모델 생성

- books/views.py
- dialogs/models.py
- requirements.txt
> bug: user모델 참조 수정

- books/models.py
- dialogs/models.py
- dialogs/views.py
- mypages/admin.py
- mypages/models.py
- mypages/serializers.py
- mypages/urls.py
- mypages/views.py
settings.AUTH_USER_MODEL을 사용하도록 일부 코드를 수정하였습니다.
퀴즈 기록, 대화기록 serializer, viewset, admin, url을 설정하였습니다.
> Refactor: settings.AUTH_USER_MODEL을 사용하도록 변경

- books/models.py
- dialogs/models.py
- dialogs/serializers.py
- dialogs/urls.py
- dialogs/views.py
- mypages/admin.py
- mypages/models.py
- mypages/serializers.py
- mypages/urls.py
- mypages/views.py
- quizzes/admin.py
- quizzes/models.py
- quizzes/serializers.py
- quizzes/urls.py
- quizzes/views.py
일부 모델을 리팩토링하고 API를 구현하였습니다. 
- 모델 수정 사항은 아래와 같습니다. 
- `Question` 모델을 `Quiz`모델로 통합(`Question` 모델은 삭제되었음)
- `ConversationRecord 모델` 삭제
- 구현된 API한 아래 이미지 속 내용과 같습니다. 노션 백엔드 페이지의 API 명세서에 기재되어 있습니다.
> Feat: 퀴즈, 대화 관련 API 구현

- books/models.py
> Feat: 캐릭터 모델에 tts 설정값 추가

- books/admin.py
- books/management/commands/load_books.py
- books/models.py
- books/serializers.py
- books/urls.py
- books/views.py
- ossKobot/settings.py
- ossKobot/urls.py
- users/management/commands/load_users.py
Feat: 책 별 나의 생각 공유, 독후감 CRUD와 몇가지 api를 구현했습니다. 관련 내용은 노션에 적어두겠습니다.
추가로 책과 유저 자동 추가 기능을 만들어 두었습니다
python manage.py load_books
python manage.py load_users
> Feat: 책 별 나의 생각 공유 관련 기능 구현

- ossKobot/settings.py
- users/adapter.py
- users/admin.py
- users/models.py
- users/serializers.py
- users/urls.py
- users/views.py
회원가입 시 생년월일 값도 입력받도록 수정하였습니다.
email 인증 구현이 완료된 branch에서 가져와서 작업하여 이메일 인증 관련 커밋 내용이 앞부분에 중복되었습니다.
> Feat: 회원가입 시 생년월일도 입력받도록 수정

- dialogs/chat_utils.py
- ossKobot/settings.py
> Build: CORS관련 설정 변경

- books/views.py
Feat: 독후감과 나의 생각 공유를 get할 때 최신순으로 정렬되어 가져오도록 하였습니다.
> Feat: 독후감과 나의 생각 공유를 get할 때 최신순으로 정렬되어 가져오도록 하였습니다.

- books/models.py
- books/serializers.py
- users/views.py
Feat: comments, post 요청 시 좋아요를 누른 유저의 id가 함께 조회되도록 변경
> Feat: 좋아요를 누른 유저의 id가 함께 조회되도록 변경

- dialogs/serializers.py
- ossKobot/settings.py
- users/urls.py
- users/views.py
> Feat: Logout 기능 추가

- dialogs/views.py
이미 존재하는 대화를 요청하면 새로 생성되지 않고 기존의 대화 id와 정보를 반환하도록 수정했습니다.
> Feat: 대화 생성 API 수정

- users/models.py
email 필드에 대해서 unique=True 속성을 추가하여 중복이 발생하지 않도록 하였습니다.
> Fix: unique 속성값 추가

- books/models.py
- books/serializers.py
- books/urls.py
- books/views.py
- ossKobot/settings.py
> Fix: Post모델 관련 기능 오류 수정

- users/views.py
Feat: 프로필 조회 시 생년월일, 프로필 이미지 위치 get하도록 수정
> Feat: 프로필 조회 시 생년월일, 프로필 이미지 위치 get하도록 수정

- ossKobot/settings.py
- users/admin.py
- users/serializers.py
- users/urls.py
- users/views.py
> Feat: 프로필 수정 기능 추가

- users/views.py
> Feat: profile_update 기능 추가

- dialogs/admin.py
- dialogs/chat_utils.py
- dialogs/models.py
- dialogs/serializers.py
- dialogs/urls.py
- dialogs/views.py
summary 모델을 통해 이전 대화를 데이터베이스에 저장하고 가져와서 맥락이 이어지는 대화 기능을 추가했습니다.
> 69 feat 챗봇 대화 요약 모델 구현

- dialogs/serializers.py
- dialogs/views.py
conversation에 대화가 끝난 시점도 저장합니다.
> Feat: conversation 모델 변경

- dialogs/urls.py
- dialogs/views.py
> Feat: 대화 끝내기 api 구현

- ossKobot/settings.py
- users/views.py
올바른 비밀번호로 변경할 수 있도록 정규식을 추가했습니다. 비밀번호 변경 실패 시 이에 맞는 에러 메세지를 띄울 수 있게 수정하였습니다.
> Feat: 비밀번호 변경 시 정규식 추가

- dialogs/models.py
- dialogs/views.py
마이페이지에서 대화 목록 조회 시 메세지가 없는 빈 대화들이 삭제되고 메세지가 있는 대화들의 리스트만 반환되도록 수정하였습니다.
> Feat: 빈 대화 삭제 기능 구현

- users/views.py
비밀번호 변경 링크를 한번 사용하면 링크가 만료되도록 설정했습니다.
> Feat: 비밀번호 변경 링크 토큰 만료 기능 추가

- books/urls.py
- books/views.py
책 제목과 저자명으로 도서를 검색할 수 있는 API를 구현하였습니다.
> Feat: 도서 검색 API 구현

- books/models.py
- books/serializers.py
- books/urls.py
- books/views.py
- ossKobot/settings.py
- users/admin.py
- users/management/commands/load_users.py
> Feat: 찜 기능 추가

- books/serializers.py
> Feat: get 시 id만 얻어오도록 수정

- books/serializers.py
- 카테고리가 한글로 출력되게끔 수정하였습니다.
- 시리얼라이저 필드에 카테고리를 추가하여 책 정보로 카테고리가 같이 출력되게끔 수정하였습니다.
> Fix: 카테고리 관련 오류 수정

- books/models.py
- books/views.py
> Feat: 추천 및 위시리스트의 책 반환 형식 변경

- books/models.py
- books/views.py
Feat: wish_count 를 추가했습니다.
개인이 찜 목록에 추가/삭제 시, Book 오브젝트에도 카운트가 올라가거나 내려가도록 했습니다.
단순 카운트로만 설정했는데, 책 별 찜 한 유저들을 반환하는 것을 원하신다면 수정 요청해주세요
> Feat: wish_count 를 추가했습니다.

- books/views.py
- dialogs/views.py
> fix: 다른 사람의 대화 내용이 보이는 버그 수정

- dialogs/views.py
fix: start_conversation 버그 수정
summary_message를 get할 때, 여러 객체가 get 되면 버그가 발생했습니다. 여러 객체 중 하나만 가져오도록 수정했고, 아마 유저 필터링이 적용이 안된 것 같아 적용도 했습니다.
> fix: start_conversation 버그 수정

- books/myBook.py
> Fix: 반환값 오류 수정

- books/serializers.py
- books/views.py
> Feat: Written Book 기본 이미지 추가 

- books/recommned_utils.py
- dialogs/chat_utils.py
추천모델, 챗봇 모델 코드 리팩토링 및  프롬프트 수정해서 성능 향상 시켰습니다.
> 146 feat chatbot upgrade

- books/models.py
- books/views.py
fix: WrittenBook을 get할 때, 다른 사용자의 책이 보이는 버그를 수정
> fix: WrittenBook을 get할 때, 다른 사용자의 책이 보이는 버그를 수정

- dialogs/chat_utils.py
> fix: prompt 수정해서 인사 여러번 하는 버그 수정했숩니다
